---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-seatunnel-nineinfra-tech-v1-seatunneljob
  failurePolicy: Fail
  name: mseatunneljob.kb.io
  rules:
  - apiGroups:
    - seatunnel.nineinfra.tech
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - seatunneljobs
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-seatunnel-nineinfra-tech-v1-seatunneljob
  failurePolicy: Fail
  name: vseatunneljob.kb.io
  rules:
  - apiGroups:
    - seatunnel.nineinfra.tech
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - seatunneljobs
  sideEffects: None
