# permissions for end users to edit seatunneljobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: seatunneljob-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: seatunnel-operator
    app.kubernetes.io/part-of: seatunnel-operator
    app.kubernetes.io/managed-by: kustomize
  name: seatunneljob-editor-role
rules:
- apiGroups:
  - seatunnel.nineinfra.tech
  resources:
  - seatunneljobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - seatunnel.nineinfra.tech
  resources:
  - seatunneljobs/status
  verbs:
  - get
