apiVersion: seatunnel.nineinfra.tech/v1
kind: SeatunnelJob
metadata:
  labels:
    app.kubernetes.io/name: seatunneljob
    app.kubernetes.io/instance: seatunneljob-sample
    app.kubernetes.io/part-of: seatunnel-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: seatunnel-operator
  name: seatunneljob-sample
spec:
  version: "v2.3.4"
  image:
    repository: "nineinfra/seatunnel"
    tag: "v2.3.4"
    pullPolicy: "IfNotPresent"
  conf:
    env:
      "spark.driver.defaultJavaOptions": "\"--add-exports java.base/sun.nio.ch=ALL-UNNAMED\""
    source:
      type: Kafka
      conf:
        "bootstrap.servers": "\"kafkacluster-sample-kafka:9092\""
        "topic": "\"nineinfra\""
    sink:
      type: HdfsFile
      conf:
          "fs.defaultFS": "\"hdfs://nineinfra\""
          "path": "\"/nineinfra/datahouse/seatunnel\""
          "tmp_path": "\"/nineinfra/datahouse/tmp\""
          "hdfs_site_path": "\"/opt/spark/conf/hdfs-site.xml\""
          "custom_filename": "true"
          "file_name_expression": "\"${now}\""
          "file_format_type": "\"text\""
          "field_delimiter": "\",\""
          "row_delimiter": "\"\\n\""
          "have_partition": "false"
          "is_partition_field_write_in_file": "false"
          "is_enable_transaction": "false"
          "batch_size": "10000000"
          "compress_codec": "\"none\""
          "remote_user": "\"kyuubi\""




